Gh 106 refactor similar screen
menta1/practicum-android-diploma pull request #115
Opened 2023-10-23 10:29 UTC by ImNia

В этой же ветке поправила свои косяки на экране с подробным описанием вакансии

2023-10-23 17:54 UTC, menta1 requested changes
Кнопка ic_favourite явно расположена не так как на макете в фигме

2023-10-23 17:59 UTC, menta1 commented
Если зарплата указано только "до 100000", то писать только "100000" без "до"

2023-10-23 18:01 UTC, menta1 commented
Лого компаний скайлится как то странно, обрезает очень сильно

2023-10-24 03:03 UTC, ImNia commented
Иконку и лого поправила, с зарплатой не согласна.
В тз написано: Уровень зарплаты отображается согласно полученным данным. Если указана только нижняя граница, то «от XX», если только верхняя — «до XX», если обе — «от XX до XX», не указана ни одна из границ, то «зарплата не указана».
Слово "до" должно указываться

2023-10-24 05:08 UTC, menta1 commented
Согласен. Смутило что на макете есть вакансия где присто зарплата написана

2023-10-24 05:16 UTC, menta1 reviewed
Вроде все ок. Единственное посмотри на кнопку Назад на экране Детали и на Похожие вакансии. Она прыгает туда сюда, на каком то экране не правильно расположена

2023-10-24 05:17 UTC, menta1 approved these changes

2023-10-24 07:36 UTC, ImNia commented
Верстка на экране с похожими вакансиями и с описанием вакансии отличаются, на экране с похожими вакансиями жестко задан отступ, а в описании он расставляет элементы относительно друг друга, надо поправить верстку у экрана с описанием, лучше сделать отдельной задачей, выглядит как будто будет много изменений

2023-10-24 07:36 UTC, merged