GH-38: Верстка фильтра отрасли
menta1/practicum-android-diploma pull request #45
Opened 2023-10-04 14:27 UTC by vlodo-o

2023-10-04 18:40 UTC, ImNia commented on app/src/main/res/layout/fragment_filter_sector.xml
> +
По макету еще есть кнопка Выбрать

2023-10-04 19:15 UTC, alexxk2 requested changes
Написал по item в комментарии. Также есть мысль, что на макете ошибка, когда введен текст. Думаю там задумывалось такое же поведение как и на экране поиска, они же одинаковые, напишу в пачку.

2023-10-04 19:15 UTC, alexxk2 commented on app/src/main/res/layout/industry_item.xml
> +        app:layout_constraintTop_toTopOf="parent"
Вроде как на макете тут textSize = 16sp
И скорее всего есть marginEnd до самой кнопки(на макете текст не подходит к кнопке вплотную), а у нас текст вплотную к ней.
Еще сама кнопка выбора слишком близко к краю экрана, на макете он почти вровень с окном поиска, а у нас нет. На макете у неё отступ 18

2023-10-04 19:47 UTC, vlodo-o commented on app/src/main/res/layout/industry_item.xml
> +        app:layout_constraintTop_toTopOf="parent"
18 многовато кажется. Вроде с 12 близко к макету получилось. Остальное поправила

2023-10-04 19:56 UTC, vlodo-o commented on app/src/main/res/layout/fragment_filter_sector.xml
> +
Добавила

2023-10-05 19:39 UTC, alexxk2 approved these changes
Все хорошо

2023-10-05 19:43 UTC, merged