GH-58: Сделал верстку экрана Region
menta1/practicum-android-diploma pull request #59
Opened 2023-10-06 19:00 UTC by menta1

2023-10-06 19:46 UTC, alexxk2 requested changes

2023-10-06 19:46 UTC, alexxk2 commented on app/src/main/res/layout/fragment_filter_region.xml
> +        <ImageView
Я бы поменял название кнопки навигации, явно тут опечатка и хорошо бы найти где еще такой лэйаут используется и исправить там тоже

2023-10-06 19:46 UTC, alexxk2 commented on app/src/main/res/layout/fragment_filter_region.xml
> +            android:layout_width="wrap_content"
Визуально неверный отступ кнопки навигации и тутула от левого края экрана(слишком большой), на макете кнопка навигации назад вровень с окном поиска, а тут уходит далеко вправо

Также нашел этот же лэайт на экране Поиск страны, там тоже он слишко далеко вправо уходит, если есть возможность тоже бы поправить

2023-10-06 19:46 UTC, alexxk2 commented on app/src/main/res/layout/fragment_filter_region.xml
> +    <ImageView
Имэдж вью ошибки "Такого региона нет" и текст надо был объединить в один LinearLayout и дать ему ID, чтобы потом было им удобно манипулировать в коде по стейтам

Также не нашел аналогичный лэйаут для ошибки "Не удалось получить список", если нет, то надо добавить

2023-10-06 19:46 UTC, alexxk2 commented on app/src/main/res/layout/button_item.xml
> +    <Button
Тут я не знаю прав я или нет, то мне кажется, что если делать такие шаблоны, то у них не должно быть своих отступов, отступы нужные уже проставить в include. Но может тут я не прав, смотри сам

2023-10-07 15:11 UTC, menta1 commented on app/src/main/res/layout/button_item.xml
> +    <Button
Я тоже сперва так хотел сделать, но потом обнаружил что поля переопределить через верстку нельзя. И соотвественно можно только использовать кнопку как есть, а где она появляется там отступ будет один и тот же

2023-10-10 15:00 UTC, alexxk2 approved these changes

2023-10-10 15:06 UTC, merged