GH-8: Добавил модели в domain
menta1/practicum-android-diploma pull request #9
Opened 2023-10-01 00:09 UTC by menta1

Добавил модели для слоя domain.

2023-10-01 01:30 UTC, alexxk2 requested changes
Норм модели, по комментариям написал, и думаю стоит все-таки добавить контактные поля в модель деталей(потом разберемся как их достать)

2023-10-01 01:30 UTC, alexxk2 commented on app/src/main/java/ru/practicum/android/diploma/domain/models/Vacancy.kt
> +    //Работодатель
Мне кажется станет понятнее, если убрать комментарии и поменять названия некоторых полей, например,
name-> vacancyName
emploer -> emploerName
currency -> salaryCurrency

глобально, чем меньше комментов - тем лучше

2023-10-01 01:30 UTC, alexxk2 commented on app/src/main/java/ru/practicum/android/diploma/domain/models/VacancyDetail.kt
> +//https://api.hh.ru/vacancies/86586739 запрос выглядит вот так
Думаю эта информация лишняя в модели, имею ввиду коммент с запросом

2023-10-01 01:30 UTC, alexxk2 commented on app/src/main/java/ru/practicum/android/diploma/domain/models/VacancyDetail.kt
> +    //Работодатель
Как уже писал, думаю стоит убрать все комментарии-пояснения к полям и немного видоизменить их названия
name -> vacancyName 
employer -> employerName и т.д.

2023-10-01 01:30 UTC, alexxk2 commented on app/src/main/java/ru/practicum/android/diploma/domain/models/VacancyDetail.kt
> +    val employment: String,
Возможно будет лучше назвать employmentType? Не уверен, что это прям лучше так что смотри сам

2023-10-01 01:30 UTC, alexxk2 commented on app/src/main/java/ru/practicum/android/diploma/domain/models/VacancyDetail.kt
> +    //Осталась информация по Контакт работодателя
Предлагаю все-таки добавить поля
val phone
val email
val contactPerson

Мы еще не поняли откуда их брать, но они нам все равно нужны, надо добавить сейчас, а как их достать из запроса потом разберемся

2023-10-01 09:18 UTC, ImNia commented on app/src/main/java/ru/practicum/android/diploma/domain/models/Vacancy.kt
> +    val currency: String,
Может стоит оставить структуру пакетов как в ответе от hh? 
Сделать отдельный класс Salary и там уже описывать валюту и границы, чтобы сам класс VacancyDetail не был большим.
```
"salary": {
        "from": 3250,
        "to": null,
        "currency": "BYR",
        "gross": false
    }
```

2023-10-01 09:18 UTC, ImNia commented on app/src/main/java/ru/practicum/android/diploma/domain/models/VacancyDetail.kt
> +    val employer: String,
И может сделать отдельный класс для информации о работодателе? Храня там его id, название и логотип.

2023-10-01 17:03 UTC, menta1 commented on app/src/main/java/ru/practicum/android/diploma/domain/models/Vacancy.kt
> +    val currency: String,
Это модель domain, сюда будем памить. А вот класс salary будет уже лежать в пакете dto.

2023-10-01 17:04 UTC, menta1 commented on app/src/main/java/ru/practicum/android/diploma/domain/models/VacancyDetail.kt
> +    val employer: String,
Не уверен что он нам нужен в domain. В пакете data будет такой класс

2023-10-01 17:05 UTC, menta1 commented on app/src/main/java/ru/practicum/android/diploma/domain/models/VacancyDetail.kt
> +    //Осталась информация по Контакт работодателя
Предлогаю добавить, когда будем точно знать на счет этих полей. А сейчас использовать поля которые нам известны

2023-10-01 17:05 UTC, menta1 commented on app/src/main/java/ru/practicum/android/diploma/domain/models/VacancyDetail.kt
> +    val employment: String,
Согласен, более инфомативно получается.

2023-10-01 17:05 UTC, menta1 commented on app/src/main/java/ru/practicum/android/diploma/domain/models/VacancyDetail.kt
> +    //Работодатель
Тут не соглашусь, так как класс уже называется Vacancy и он сам за себя говорит

2023-10-01 17:06 UTC, menta1 commented on app/src/main/java/ru/practicum/android/diploma/domain/models/VacancyDetail.kt
> +//https://api.hh.ru/vacancies/86586739 запрос выглядит вот так
убрал

2023-10-01 17:17 UTC, vlodo-o approved these changes

2023-10-02 10:40 UTC, alexxk2 approved these changes

2023-10-02 10:40 UTC, merged